Description: Configuration for CANoe participant for SIL Kit Adapter vcan Demo
Logging:
  Sinks:
    - Level: Info
      Type: Stdout
CanControllers:
 - Name: "CAN"
   Network: "CAN1"

Middleware:
  RegistryUri: silkit://localhost:8501