Description: Configuration for Adapter participant for SIL Kit Adapter vcan demo
ParticipantName: SilKitAdapterVcan
CanControllers:
- Name: SilKit_CAN_CTRL_1
  Network: CAN1
Middleware:
  RegistryUri: silkit://localhost:8501
Logging:
  Sinks:
  - Type: Stdout
    Level: Debug